[tool.isort]
profile = "black"
line_length = 79
known_local_folder = ["lib"]

[tool.black]
line-length = 79

[tool.pytest.ini_options]
addopts = "--cov-report=term-missing --cov=lib"

[tool.coverage.run]
plugins = ["coverage_conditional_plugin"]

[tool.coverage.coverage_conditional_plugin.rules]
py-gte-38 = "sys_version_info >= (3, 8)"
